language: go

os:
  - linux
  - osx

go:
  - 1.13.x
  - 1.14.x

install:
  - make install-tools

script:
  - make lint
  - make test-verbose-with-coverage
  - gover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then goveralls -coverprofile=gover.coverprofile -service=travis-ci; fi
